spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=LoanDB;encrypt=true;trustServerCertificate=true"
    username: bot
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  # Redis Configuration
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60000ms
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in milliseconds

  # Spring Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: afitsantosowork@gmail.com # Ganti dengan email Anda
    password: maah fezk vvis ashr # Ganti dengan App Password Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    test-connection: false # Set false agar tidak error saat startup jika belum konfigurasi email

file:
  upload-dir: ./uploads/kyc

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: "genggamin-secret-key-change-this-in-production-with-stronger-key"
    expiration: 86400000 # 24 hours in milliseconds
  frontend:
    url: https://genggamin-fe.vercel.app/ # URL frontend untuk link reset password di email
  google:
    client-id: "926562784828-316arit97i791egpso2t8qk9muuqq4nf.apps.googleusercontent.com"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
